PROTO_ROOT_DIR = $(shell brew --prefix)/Cellar/protobuf/3.7.0/include
VERSION=0.1.0

default: clean stubs

## Dart requires you to manually ship all google provided proto files too.
stubs:
	mkdir -p lib/generated
	protoc -I=protos --dart_out=grpc:lib/generated protos/*.proto
	protoc -I$(PROTO_ROOT_DIR) --dart_out=lib/generated $(PROTO_ROOT_DIR)/google/protobuf/*.proto

clean:
	rm -rf build lib/generated

run-local:
	dart bin/server.dart

build-docker:
	docker build -t pambrose/flutter_module:${VERSION} .

run-docker:
	docker run -p 50051:50051 pambrose/flutter_module:${VERSION}

push-docker:
	docker push pambrose/flutter_module:${VERSION}
